services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - COHERE_API_KEY=6Mm7a7vPMSvwp5VKZU4MQuIrjSm1M0yOAwW1zaDY
    volumes:
      - backend_data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  backend_data: